In [34]:
import numpy as np

In [94]:
checkboard_size = 15

cb = np.zeros([checkboard_size,checkboard_size])

In [44]:
black_step = 1
white_step = 2

turn = 1
black_turn = 1
white_turn = 2

In [61]:
cb = np.ones([10,10])

In [97]:
cb = np.ones([15,15])
for i in range(15):
    cb[i,1] = 2
    cb[i,3] = 2
    cb[i,6] = 2
    cb[i,7] = 2


In [105]:
cb

array([[1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2.

In [131]:
##判斷直
ct = 0
g = 1
checkboard_size = 15
for j in range(checkboard_size):
    if g ==0:
        break
    for i in range(checkboard_size):
        tmp = cb[i,j]
        if tmp == turn:
            ct+=1
            if ct==5:
                print("gameover")
                g =0
                break
            
        else:
            ct =0


gameover


In [116]:
cb

array([[1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 1., 2., 1., 1., 2.

In [133]:
##判斷橫            
ct = 0
g = 1
checkboard_size = 15
for i in range(checkboard_size):
    if g ==0:
        break
    for j in range(checkboard_size):
        tmp = cb[i,j]
        
        if tmp == turn:
            ct+=1
            
            if ct==5:
                print("gameover")
                g = 0

                break
            
        else:
            ct =0
            continue

gameover


In [172]:
## 判斷斜線
for i in range(checkboard_size):
    for j in range(checkboard_size):
        
        if i+1<checkboard_size and i+2<checkboard_size and i+3<checkboard_size and i+4<checkboard_size and j+1<checkboard_size and j+2<checkboard_size and j+3<checkboard_size and j+4<checkboard_size:
            if cb[i,j] == cb[i+1,j+1] == cb[i+2,j+2] == cb[i+3,j+3] == cb[i+4,j+4] == turn:
                print("gameover")
                break
                

gameover


In [169]:
tmp

1.0

In [213]:
def win(checkboard_size,turn):
    ct = 0
    g = 1
    for j in range(checkboard_size):
        if g ==0:
            break
        for i in range(checkboard_size):
            tmp = cb[i,j]
            if tmp == turn:
                ct+=1
                if ct==5:
                    print("gameover")
                    g =0
                    return True
            
            else:
                ct =0

    ##判斷橫            
    ct = 0
    g = 1
    for i in range(checkboard_size):
        if g ==0:
            break
        for j in range(checkboard_size):
            tmp = cb[i,j]

            if tmp == turn:
                ct+=1

                if ct==5:
                    print("gameover")
                    g = 0

                    return True

            else:
                ct =0
                continue
    ## 判斷斜線
    for i in range(checkboard_size):
        for j in range(checkboard_size):

            if i+1<checkboard_size and i+2<checkboard_size and i+3<checkboard_size and i+4<checkboard_size and j+1<checkboard_size and j+2<checkboard_size and j+3<checkboard_size and j+4<checkboard_size:
                if cb[i,j] == cb[i+1,j+1] == cb[i+2,j+2] == cb[i+3,j+3] == cb[i+4,j+4] == turn:
                    print("gameover")
                    return True
    
    return False
                
    
    
    

In [215]:
## 左下角為 (0,0)
checkboard_size = 5
cb = np.zeros([checkboard_size,checkboard_size])

turn = 1
steps = 0

while True:
    if turn == black_turn:
        print("now is black turn")
    x = input("your moves")
    if x == "q":
        break
    x = x.split(",")
    
    while turn == black_turn :
        step_r = int(x[0])
        step_c = int(x[1])
        
        steps = cb[checkboard_size-1 - step_r, step_c]
          
        if steps == 0: ## place with no piece
            cb[checkboard_size-1 - step_r, step_c] = black_step
            turn = white_turn
            print(cb)
            break
        else:
            print("there is already a piece in the place, redetermine ur step")
            turn = black_turn
            break
    if win(checkboard_size,1):
        break
        
    if turn == white_turn:
        print("now is white turn")
        
    x = input("your moves")
    if x == "q":
        break
    x = x.split(",")
    
    while turn == white_turn:
        step_r = int(x[0])
        step_c = int(x[1])
        
        steps = cb[checkboard_size-1 - step_r, step_c]
        
        if steps == 0: ## place with no piece
            cb[checkboard_size-1 - step_r, step_c] = white_step
            turn = black_turn
            print(cb)
            break
        else:
            print("there is already a piece in the place, redetermine ur step")
            turn = white_turn
            break
    if win(checkboard_size,2):
        break
        
    
    
    
    
    
    
    

now is black turn
your moves0,0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
now is white turn
your moves0,1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 2. 0. 0. 0.]]
now is black turn
your moves1,1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 2. 0. 0. 0.]]
now is white turn
your moves2,1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 2. 0. 0. 0.]]
now is black turn
your moves2,2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 2. 0. 0. 0.]]
now is white turn
your moves2,3
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 1. 2. 0.]
 [0. 1. 0. 0. 0.]
 [1. 2. 0. 0. 0.]]
now is black turn
your moves4,4
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 2. 1. 2. 0.]
 [0. 1. 0. 0. 0.]
 [1. 2. 0. 0. 0.]]
now is white turn
your moves2,4
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 2. 1. 2. 2.]
 [0. 1. 0. 0. 0.]
 [1. 2. 0. 0. 0.]]
now is black tur

In [188]:
cb

array([[2., 0., 0., 0., 1.],
       [2., 0., 0., 1., 0.],
       [2., 0., 1., 0., 0.],
       [2., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [198]:
for i in range(checkboard_size):
    for j in range(checkboard_size):

        if i+1<checkboard_size and i+2<checkboard_size and i+3<checkboard_size and i+4<checkboard_size and j+1<checkboard_size and j+2<checkboard_size and j+3<checkboard_size and j+4<checkboard_size:
            if cb[i,j] == cb[i+1,j+1] == cb[i+2,j+2] == cb[i+3,j+3] == cb[i+4,j+4] == turn:
                print("gameover")
                break
                
for i in range(checkboard_size):
    for j in range(checkboard_size):

        if i+1<checkboard_size and i+2<checkboard_size and i+3<checkboard_size and i+4<checkboard_size and j+1<checkboard_size and j+2<checkboard_size and j+3<checkboard_size and j+4<checkboard_size:
            if cb[4-i,j] == cb[4-i-1,j+1] == cb[4-i-2,j+2] == cb[4-i-3,j+3] == cb[4-i-4,j+4] == turn:
                print("gameover")
                break

In [200]:
cb

array([[1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 0.],
       [0., 0., 1., 2., 0.],
       [2., 2., 0., 1., 2.],
       [2., 2., 0., 0., 1.]])

In [208]:
for i in range(checkboard_size):
    for j in range(checkboard_size):

        if i+1<checkboard_size and i+2<checkboard_size and i+3<checkboard_size and i+4<checkboard_size and j+1<checkboard_size and j+2<checkboard_size and j+3<checkboard_size and j+4<checkboard_size:
            print("pass")
            if cb[i,j] == cb[i+1,j+1] == cb[i+2,j+2] == cb[i+3,j+3] == cb[i+4,j+4] == turn:
                print("gameover")
                break

pass
gameover


In [205]:
cb[1,1]

1.0

In [207]:
turn =1