In [2]:
import numpy as np

In [3]:
black_step = 1
white_step = 2

turn = 1
black_turn = 1
white_turn = 2    

In [6]:
cb_size = 5

cb = np.zeros([checkboard_size,checkboard_size])

In [5]:
cb

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
for i in range(cb_size):
    cb[i,i] = 1

In [8]:
cb

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
for i in range(cb_size):
    cb[i,0] = 1

In [10]:
cb

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.]])

In [11]:
for i in range(cb_size):
    cb[0,i] = 1

In [12]:
cb

array([[1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1.]])

In [21]:
##判斷直
ct = 0
g = 1
checkboard_size = 15
for j in range(cb_size):
    if g ==0:
        break
    for i in range(cb_size):
        tmp = cb[i,j]
        if tmp == turn:
            ct+=1
            if ct==5:
                print("gameover")
                g =0
                break
            
        else:
            ct =0

gameover


In [30]:
##判斷橫            
ct = 0
g = 1
for i in range(cb_size):
    if g ==0:
        break
    for j in range(cb_size):
        tmp = cb[i,j]
        
        if tmp == turn:
            ct+=1
            
            if ct==5:
                print("gameover")
                g = 0

                break
            
        else:
            ct =0
            continue

gameover


In [85]:
## 判斷斜線
for i in range(cb_size):
    for j in range(cb_size):
        
        if i+1<cb_size and i+2<cb_size and i+3<cb_size and i+4<cb_size:
            if j+1<cb_size and j+2<cb_size and j+3<cb_size and j+4<cb_size:
                if cb[i,j] == cb[i+1,j+1] == cb[i+2,j+2] == cb[i+3,j+3] == cb[i+4,j+4] == turn:
                    print("gameover")
                    break
            

In [87]:
## 判斷斜線
for i in range(cb_size):
    for j in range(cb_size):
        
        if i-1>0 and i-2>0 and i-3>0 :
            if j+1 <cb_size and j+2<cb_size and j+3<cb_size and j+4<cb_size:
                if cb[i,j] == cb[i-1,j+1] == cb[i-2,j+2] == cb[i-3,j+3] == cb[i-4,j+4] == turn:
                    print("gameover")
                    break

gameover


In [86]:
cb

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 2.],
       [0., 2., 1., 2., 2.],
       [0., 1., 2., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [88]:
def gameover():
    ## 判斷斜線
    for i in range(cb_size):
        for j in range(cb_size):

            if i+1<cb_size and i+2<cb_size and i+3<cb_size and i+4<cb_size:
                if j+1<cb_size and j+2<cb_size and j+3<cb_size and j+4<cb_size:
                    if cb[i,j] == cb[i+1,j+1] == cb[i+2,j+2] == cb[i+3,j+3] == cb[i+4,j+4] == turn:
                        print("gameover")
                        return True 
        ## 判斷斜線
    for i in range(cb_size):
        for j in range(cb_size):

            if i-1>0 and i-2>0 and i-3>0 :
                if j+1 <cb_size and j+2<cb_size and j+3<cb_size and j+4<cb_size:
                    if cb[i,j] == cb[i-1,j+1] == cb[i-2,j+2] == cb[i-3,j+3] == cb[i-4,j+4] == turn:
                        print("gameover")
                        return True
    ##判斷橫            
    ct = 0
    g = 1
    
    for i in range(cb_size):
        if g ==0:
            break
        for j in range(cb_size):
            tmp = cb[i,j]

            if tmp == turn:
                ct+=1

                if ct==5:
                    print("gameover")
                    g = 0
                    return True

            else:
                ct =0
                continue
            
    ##判斷直
    ct = 0
    g = 1
    checkboard_size = 15
    for j in range(cb_size):
        if g ==0:
            break
        for i in range(cb_size):
            tmp = cb[i,j]
            if tmp == turn:
                ct+=1
                if ct==5:
                    print("gameover")
                    g =0
                    return True

            else:
                ct =0
    
    
    return False

In [89]:
gameover()

gameover


True

In [90]:
def play():
    turn = 1
    steps = 0
    global cb 
    cb = np.zeros([cb_size,cb_size])
    while True:
        
        ## black
        if turn == black_turn:
            print("now is black turn")
        x = input("your moves")
        if x == "q":
            break
        x = x.split(",")

        while turn == black_turn :
            step_r = int(x[1])
            step_c = int(x[0])

            steps = cb[cb_size-1 - step_r, step_c]

            if steps == 0: ## place with no piece
                cb[cb_size-1 - step_r, step_c] = black_step
                turn = white_turn
                print(cb)
                break
            else:
                print("there is already a piece in the place, redetermine ur step")
                turn = black_turn
                break
        if gameover():
            break
#########################################################################
        
        ##white
        if turn == white_turn:
            print("now is white turn")

        x = input("your moves")
        if x == "q":
            break
        x = x.split(",")

        while turn == white_turn:
            step_r = int(x[1])
            step_c = int(x[0])

            steps = cb[cb_size-1 - step_r, step_c]

            if steps == 0: ## place with no piece
                cb[cb_size-1 - step_r, step_c] = white_step
                turn = black_turn
                print(cb)
                break
            else:
                print("there is already a piece in the place, redetermine ur step")
                turn = white_turn
                break
        if gameover():
            break


In [91]:
play()

now is black turn
your moves0,0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]
now is white turn
your moves1,0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 2. 0. 0. 0.]]
now is black turn
your moves1,1
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 2. 0. 0. 0.]]
now is white turn
your moves2,0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 2. 2. 0. 0.]]
now is black turn
your moves2,2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 2. 2. 0. 0.]]
now is white turn
your moves3,0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 2. 2. 2. 0.]]
now is black turn
your moves3,3
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 2. 2. 2. 0.]]
now is white turn
your moves4,0
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 2. 2. 2. 2.]]
now is black tur

In [60]:
turn

1

In [69]:
cb

array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 2., 2., 0.],
       [1., 0., 2., 2., 0.]])

In [70]:
gameover()

False